name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_SSH_USERNAME }}@${{ secrets.DROPLET_SSH_HOST }} << 'EOF'
          set -e

          # Diretório do projeto no servidor
          PROJECT_DIR="/home/servemei-phyton"
          REPO_URL="https://github.com/ServelojaDev/servemei-phyton-selenium.git"  # Mudança para HTTP

          # Atualize ou clone o repositório
          if [ ! -d "$PROJECT_DIR" ]; then
              echo "Clonando o repositório..."
              git clone $REPO_URL $PROJECT_DIR
          else
              echo "Atualizando o repositório..."
              cd $PROJECT_DIR
              git pull
          fi

          # Certifique-se de que está no diretório do projeto
          cd $PROJECT_DIR

          # Configure o virtual environment
          if [ ! -d "venv" ]; then
              echo "Criando o virtual environment..."
              python3 -m venv venv
          fi

          # Ative o virtual environment e instale as dependências
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate

          echo "Deploy concluído com sucesso."
          EOF
