name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_SSH_USERNAME }}@${{ secrets.DROPLET_SSH_HOST }} << 'EOF'
          set -e

          # Diretório do projeto no servidor
          PROJECT_DIR="/home/servemei-phyton"

          # Atualize o repositório
          if [ ! -d "$PROJECT_DIR" ]; then
             git clone git@github.com:ServelojaDev/servemei-phyton-selenium.git $PROJECT_DIR
          else
              cd $PROJECT_DIR
              git pull
          fi

          # Instale dependências Python
          cd $PROJECT_DIR
          source venv/bin/activate
          pip install -r requirements.txt

          EOF
